# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.5.0
maven_group=com.mentality.customenchants
archives_base_name=custom-enchants

# Dependencies
fabric_api_version=0.92.7+1.20.1
cloth_config_version=11.1.118